[project]
name = "mcp-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.29.5",
    "mcp[cli]>=1.5.0",
    "openai>=1.68.2",
    "requests>=2.32.3",
]
